name: NPM Custom Action
description: Installing and caching NPM packages
inputs:
  cache-folder: 
    description: The path of folder to cache
    required: true
runs:
  using: 'composite'
  steps:
    - name: Cache NPM dependencies
      uses: actions/cache/@v3
      with:
        path: ${{ inputs.cache-folder }}
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      run: npm install

# Usage
- name: Usage of composite action - Cache and install NPM packages
  uses: ./.github/custom-actions/action.yml
  with:
    cache-folder: node_modules