name: Deployment - Reusable workflow

on:
  workflow_call:
    inputs:
      mongodb-uri:
        required: true
        type: string
    secrets:
      k8s-kubeconfig:
        required: true
      mongodb-password:
        required: true

jobs:
  reuse-deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'
      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      
      - name: Fetch Kubernetes Cluster Info
        run: |
          kubectl version --short -o yaml
      - name: Fetch Ingress IP
        run: echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV
      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: "['kubernetes/development/*.yaml']"
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
          INGRESS_IP: '${{ env.INGRESS_IP }}'
      - name: Verify replaced tokens
        run: cat kubernetes/development/*.yaml